version: '3.9'

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: parking-keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    depends_on:
      - postgres
    build: ./.docker/keycloak
    container_name: dev_keycloak
    restart: unless-stopped
    ports:
      - '8443:8443'
