version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:14.2-alpine
    container_name: parking-keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  keycloak:
    depends_on:
      - postgres
    build: ./.docker/keycloak
    container_name: dev_keycloak
    restart: unless-stopped
    ports:
      - '8080:8080'
