version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  parking-share-db:
    image: postgres:14.2-alpine
    container_name: parking_postgres
    restart: unless-stopped
    env_file:
      - .docker/.env
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/pg-init-scripts/:/pg-init-scripts
    ports:
      - '5432:5432'

  parking-share-keycloak:
    container_name: parking_keycloak
    depends_on:
      - parking-share-db
    build: ./.docker/keycloak
    restart: unless-stopped
    ports:
      - '8080:8080'
