server:
  port: 9090

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/parking'
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

keycloak:
  realm: parking-share
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: api
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: kek

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
